### PR TITLE
Update HomeScreen.js

### PR DESCRIPTION
**Pull request by code-arnab**
Hi, CodeGautamYT I made some changes in this HomeScreen.js hope it helps

### CODE REVIEW

**Comment by codergautam** [comment]
I will try this out, if it works I will award you the bounty, thank you!

**Comment by codergautam** [comment]
Doesn't work, stuck on loading screen even on Dev build which was working before. Please check and see what's wrong.

**Comment by codergautam** [comment]
Update: I was able to fix this myself, without the help of this PR. Basically there was a memory leak issue that kept creating new listeners on each screen load. Fixed in https://github.com/codergautam/CPSTest/commit/d2896ab320273012d9c7ddb6449522775b4f253e

Thanks for the help though! Really appreciate it.

**Comment by code-arnab** [comment]
That's great! Feel free to contact me for future projects

**Comment by codergautam** [comment]
Will do.

**Pull request merged**
